# Generated by Django 5.0.4 on 2024-04-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='date_updated',
        ),
    ]
