# Generated by Django 5.0.4 on 2024-04-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_sale_sub_total_remove_sale_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
